//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskSolutionLibrary.ModelLibrary.EntityFrameworkLibrary.ThirdPartyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardAccountRequests_UBA
    {
        public int id { get; set; }
        public string NameOnCard { get; set; }
        public string PAN { get; set; }
        public Nullable<int> PrintStatus { get; set; }
        public string UserPrinting { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public string printedName { get; set; }
        public string HolderIDNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string HolderAddress { get; set; }
        public byte[] HolderPhoto { get; set; }
        public string InstitutionName { get; set; }
        public string DateOfBirth { get; set; }
        public string Sex { get; set; }
    }
}
