//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskSolutionLibrary.ModelLibrary.EntityFrameworkLibrary.ThirdPartyData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CardIssuanceKIOSKEntities : DbContext
    {
        public CardIssuanceKIOSKEntities()
            : base("name=CardIssuanceKIOSKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardAccountRequest> CardAccountRequests { get; set; }
        public virtual DbSet<CardAccountRequests_UBA> CardAccountRequests_UBA { get; set; }
        public virtual DbSet<HubMaster> HubMasters { get; set; }
        public virtual DbSet<PANDetail> PANDetails { get; set; }
        public virtual DbSet<PANDetailsold> PANDetailsolds { get; set; }
        public virtual DbSet<PrinterTypeDetail> PrinterTypeDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<OTPDetail> OTPDetails { get; set; }
    }
}
