//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskSolutionLibrary.ModelLibrary.EntityFrameworkLibrary.ThirdPartyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPDetail
    {
        public long id { get; set; }
        public string PAN { get; set; }
        public string OTP { get; set; }
        public Nullable<System.DateTime> DateofOTP { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
