//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskSolutionLibrary.ModelLibrary.EntityFrameworkLibrary.ThirdPartyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PANDetail
    {
        public long id { get; set; }
        public string pan { get; set; }
        public string seq_nr { get; set; }
        public string expiry_date { get; set; }
        public string account_number { get; set; }
        public string account_type { get; set; }
        public string customer_id { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
