//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskSolutionLibrary.ModelLibrary.EntityFrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardRequest
    {
        public long ID { get; set; }
        public long CustomerID { get; set; }
        public string CardType { get; set; }
        public long PickupBranchID { get; set; }
        public string RequestType { get; set; }
        public string Status { get; set; }
        public string ModifiedDate { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
