//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskSolutionLibrary.ModelLibrary.EntityFrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CardRequests = new HashSet<CardRequest>();
        }
    
        public long ID { get; set; }
        public string Lastname { get; set; }
        public string Othernames { get; set; }
        public string AccountNumber { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<CardRequest> CardRequests { get; set; }
    }
}
